apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: mytestapp 
spec:
  replicas: 2 
  selector:
   matchLabels:
    app: mytestapp 
  template:
    metadata: 
      labels:
        app: mytestapp
    spec:
      containers:
      - name: mytestapp
        image: gcr.io/devops-alps-281914/alpsmathews/sprint6dockerjenkinsgcloud@sha256:1705764a31c51fd57682b714314f0357e065df576f816abfbaa032f6c2c8eaba
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: mytestapp-svc 
  labels:
    app: mytestapp 
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP 
    port: 8086
    targetPort: 8080 
  selector:
    app: mytestapp
